### ISSUE TITLE
including daea in keywords in digital humanities

### ISSUE THREAD

**Issue by shawngraham** [msu-anthropology/daea#9]
Hi folks,

I'm compiling the 'history' entry for the keywords in the digital humanities project. I'd like to include the DAEA as an exemplar in that entry. I wondered what kind of reuse license you envisioned for the project?
cheers,
Shawn

**Comment by watrall** [comment]
We're currently restructuring the way in which this project runs.  We're going to have a repo/class instance (with a corresponding website).  Then, we're going to have the best entries feed into a "best of all classes" repo (with corresponding website). This repo is the start of that process.  For your thing, you might want to reference the Fall Semester 2014 instance of the class/project - https://github.com/matrix-msu/daea-fs14

This has a license attached to it.

**Comment by geyerbri** [comment]
This repo may be moving to a new user/organization as well, though I am unsure if we can pull off the move without messing up the forks that exist elsewhere.

**Comment by geyerbri** [comment]
Shawn, this repo has been transferred to the organization msu-anthropology.

If you have linked to the repo somewhere, you'll need to update the url accordingly. GitHub states that it will forward traffic to the correct location, but this may not work because I'm creating a specific repo at the old address to explain the move and give the new link.

**Comment by shawngraham** [comment]
thanks for the headsup!
